"""initial schema

Revision ID: 8d83caca5c4a
Revises: 
Create Date: 2026-04-01 16:55:10.957581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d83caca5c4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_log_created', 'llm_usage_log', ['created_at'], unique=False)
    op.create_index('idx_llm_log_feature', 'llm_usage_log', ['feature'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('english_level', sa.String(length=10), server_default='A1', nullable=False),
    sa.Column('learning_goal', sa.String(length=50), nullable=True),
    sa.Column('bot_language_mix', sa.Integer(), server_default='10', nullable=False),
    sa.Column('active_challenge_id', sa.BigInteger(), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_challenge_id'], ['challenges.id'], name='fk_users_active_challenge', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index('idx_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('schedule_days', sa.ARRAY(sa.Integer()), server_default='{1,2,3,4,5}', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='Europe/Moscow', nullable=False),
    sa.Column('report_deadline_time', sa.Time(), server_default='23:59', nullable=False),
    sa.Column('digest_time', sa.Time(), server_default='22:00', nullable=False),
    sa.Column('reminder_time', sa.Time(), server_default='20:00', nullable=False),
    sa.Column('wotd_time', sa.Time(), server_default='08:00', nullable=False),
    sa.Column('quiz_window_start', sa.Time(), server_default='12:00', nullable=False),
    sa.Column('quiz_window_end', sa.Time(), server_default='15:00', nullable=False),
    sa.Column('features_enabled', postgresql.JSONB(astext_type=sa.Text()), server_default='{"daily_digest": true, "reminders": true, "word_of_day": true, "pop_quiz": true, "weekly_battles": true, "weekly_digest": true}', nullable=False),
    sa.Column('scoring_multipliers', postgresql.JSONB(astext_type=sa.Text()), server_default='{"speaking": 2, "listening": 1, "reading": 1.5, "writing": 2, "vocabulary": 3, "grammar": 5, "app_practice": 10, "other": 5, "wotd_bonus": 20, "quiz_correct": 15, "quiz_speed_bonus": 10}', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index('idx_challenges_active_chat', 'challenges', ['chat_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('conversation_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('feature', sa.String(length=30), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ch_created', 'conversation_history', ['created_at'], unique=False)
    op.create_index('idx_ch_user', 'conversation_history', ['user_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_type', sa.String(length=30), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_option', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quizzes_challenge', 'quizzes', ['challenge_id'], unique=False)
    op.create_index('idx_quizzes_status', 'quizzes', ['status'], unique=False)
    op.create_table('user_challenges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_report_date', sa.Date(), nullable=True),
    sa.Column('total_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_reports', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_days_in_challenge', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vacation_until', sa.Date(), nullable=True),
    sa.Column('vacation_days_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('activity_stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{"speaking_minutes": 0, "listening_minutes": 0, "reading_minutes": 0, "writing_minutes": 0, "vocabulary_count": 0, "grammar_lessons": 0, "app_lessons": 0}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id')
    )
    op.create_index('idx_uc_challenge', 'user_challenges', ['challenge_id'], unique=False)
    op.create_index('idx_uc_last_report', 'user_challenges', ['last_report_date'], unique=False)
    op.create_index('idx_uc_status', 'user_challenges', ['status'], unique=False)
    op.create_index('idx_uc_user', 'user_challenges', ['user_id'], unique=False)
    op.create_table('weekly_battles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wb_challenge', 'weekly_battles', ['challenge_id'], unique=False)
    op.create_table('words_of_the_day',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('pronunciation', sa.String(length=255), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'posted_date')
    )
    op.create_index('idx_wotd_challenge', 'words_of_the_day', ['challenge_id'], unique=False)
    op.create_table('battle_pairs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('battle_id', sa.BigInteger(), nullable=False),
    sa.Column('player1_id', sa.BigInteger(), nullable=False),
    sa.Column('player2_id', sa.BigInteger(), nullable=True),
    sa.Column('player1_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('player2_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('loser_penalty_task', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['weekly_battles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player1_id'], ['user_challenges.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['user_challenges.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['user_challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bp_battle', 'battle_pairs', ['battle_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='group', nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('wotd_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('wotd_bonus_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('llm_parse_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_challenge_id'], ['user_challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_challenge_id', 'report_date')
    )
    op.create_index('idx_reports_date', 'daily_reports', ['report_date'], unique=False)
    op.create_index('idx_reports_date_points', 'daily_reports', ['report_date', 'total_points'], unique=False)
    op.create_index('idx_reports_date_uc', 'daily_reports', ['user_challenge_id', 'report_date'], unique=False)
    op.create_index('idx_reports_uc', 'daily_reports', ['user_challenge_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('user_challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_first_correct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('points_earned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_challenge_id'], ['user_challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'user_challenge_id')
    )
    op.create_index('idx_qa_quiz', 'quiz_answers', ['quiz_id'], unique=False)
    op.create_table('report_activities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['daily_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activities_category', 'report_activities', ['category'], unique=False)
    op.create_index('idx_activities_report', 'report_activities', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activities_report', table_name='report_activities')
    op.drop_index('idx_activities_category', table_name='report_activities')
    op.drop_table('report_activities')
    op.drop_index('idx_qa_quiz', table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index('idx_reports_uc', table_name='daily_reports')
    op.drop_index('idx_reports_date_uc', table_name='daily_reports')
    op.drop_index('idx_reports_date_points', table_name='daily_reports')
    op.drop_index('idx_reports_date', table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index('idx_bp_battle', table_name='battle_pairs')
    op.drop_table('battle_pairs')
    op.drop_index('idx_wotd_challenge', table_name='words_of_the_day')
    op.drop_table('words_of_the_day')
    op.drop_index('idx_wb_challenge', table_name='weekly_battles')
    op.drop_table('weekly_battles')
    op.drop_index('idx_uc_user', table_name='user_challenges')
    op.drop_index('idx_uc_status', table_name='user_challenges')
    op.drop_index('idx_uc_last_report', table_name='user_challenges')
    op.drop_index('idx_uc_challenge', table_name='user_challenges')
    op.drop_table('user_challenges')
    op.drop_index('idx_quizzes_status', table_name='quizzes')
    op.drop_index('idx_quizzes_challenge', table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index('idx_ch_user', table_name='conversation_history')
    op.drop_index('idx_ch_created', table_name='conversation_history')
    op.drop_table('conversation_history')
    op.drop_index('idx_challenges_active_chat', table_name='challenges', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('challenges')
    op.drop_index('idx_users_telegram_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_llm_log_feature', table_name='llm_usage_log')
    op.drop_index('idx_llm_log_created', table_name='llm_usage_log')
    op.drop_table('llm_usage_log')
    # ### end Alembic commands ###
